# Generated by Django 4.2.30 on 2026-07-08 13:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2026, 7, 8)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Under Maintenance')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='message',
            field=models.TextField(blank=True, help_text='Any message or request details', null=True),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='core.property'),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests_made', to='core.tenant'),
        ),
    ]
