# Generated by Django 4.2.30 on 2026-08-01 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_payment_method_alter_payment_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='lead_email',
            field=models.EmailField(blank=True, help_text='Email from guest inquiry', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='lead_name',
            field=models.CharField(blank=True, help_text='Full name from guest inquiry', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='lead_phone',
            field=models.CharField(blank=True, help_text='Phone number from guest inquiry', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant submitting the request (null for guest/lead inquiries)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_applications', to='core.tenant'),
        ),
    ]
