# Generated by Django 4.2.30 on 2026-08-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rentalrequest_lead_email_rentalrequest_lead_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(default=1, help_text='Number of bathrooms'),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(default=1, help_text='Number of bedrooms'),
        ),
        migrations.AddField(
            model_name='property',
            name='square_feet',
            field=models.PositiveIntegerField(blank=True, help_text='Property size in square feet', null=True),
        ),
    ]
