# Generated by Django 4.2.30 on 2026-08-01 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_property_bathrooms_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='registered_by',
            field=models.ForeignKey(blank=True, help_text='Landlord who registered this tenant (null for self-registered)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_tenants', to='core.landlord'),
        ),
    ]
