# Generated by Django 4.2.30 on 2026-08-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tenant_registered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='photos',
            field=models.JSONField(blank=True, default=list, help_text='Array of base64 image strings for property photos'),
        ),
    ]
