# Generated by Django 4.2.30 on 2026-08-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_property_photos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterUniqueTogether(
            name='rentalrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payment',
            name='issued_by',
            field=models.CharField(blank=True, help_text='Name of the person/system that issued the receipt', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AddIndex(
            model_name='landlord',
            index=models.Index(fields=['full_name', 'id_number'], name='core_landlo_full_na_03b085_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['status', 'tenant', 'property'], name='core_lease_status_d828d6_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['status', 'property'], name='core_mainte_status_a26c48_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'landlord'], name='core_proper_status_c2707a_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalrequest',
            index=models.Index(fields=['status', 'landlord', 'property'], name='core_rental_status_c72ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['full_name', 'id_number'], name='core_tenant_full_na_d8b499_idx'),
        ),
    ]
