# Generated by Django 4.2.30 on 2026-08-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='landlord',
            name='core_landlo_full_na_03b085_idx',
        ),
        migrations.RemoveIndex(
            model_name='lease',
            name='core_lease_status_d828d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenance',
            name='core_mainte_status_a26c48_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='core_proper_status_c2707a_idx',
        ),
        migrations.RemoveIndex(
            model_name='rentalrequest',
            name='core_rental_status_c72ed6_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenant',
            name='core_tenant_full_na_d8b499_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='photos',
            field=models.JSONField(blank=True, default=list, help_text='Array of base64 image strings for property photos'),
        ),
        migrations.AlterUniqueTogether(
            name='rentalrequest',
            unique_together={('property', 'tenant')},
        ),
    ]
